"""数据库

Revision ID: 96a0aeee729f
Revises: 
Create Date: 2021-10-01 17:20:35.666175

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '96a0aeee729f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msgs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('body', sa.Text(), nullable=True),
                    sa.Column('body_html', sa.Text(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('author_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_msgs_timestamp'), 'msgs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_msgs_timestamp'), table_name='msgs')
    op.drop_table('msgs')
    # ### end Alembic commands ###
